const layoutData = {
  "1": "A Single Card\nFor insights into any situation that relates to your living today. Or as a basis for meditating now.",
  "2": "Relating - \"A Quickie\"\nThis spread offers a spontaneous insight into your relating with the other, whether \"the other\" is the boss, the lover, the friend, the sister, the parent...\n\n1- You and what you are contributing to the relating here/now.\n2- The other, the other's input to the relating \n3- The composite energies\n4- The insight",
  "3": "The Diamond\nThis layout can be helpful in bringing more clarity to a specific issue.\n\n1- The issue\n2- Internal influence that you are unable to see\n3- External influence of which you are aware\n4- What is needed for resolution \n5- Resolution: the understanding",
  "4": "The Flying Bird\nThis layout is designed in the shape of a bird taking flight.  The cards chosen and placed in the left wing symbolize and indicate to us something about our feminine, receptive energy, while the right wing symbolizes our masculine, active energy.  The first card picked is the initiator of the flight and stems from this active side.  Each succeeding card responds to the previous one and lifts \"the bird\" higher, allowing the questioner to move into greater clarity and inner understanding.\n\n1- Here & now — the 'lift-off\" card\n2- The resistance card - 'fear of flying' \n3- Response-ability to the fear\n4- Inner support (intuition) of responsibility\n5- External support (intelligent action responding to the intuition)\n6- Relaxation and acceptance\n7- Arrival at a new level of awareness",
  "5": "The Key\n\"The Key\" layout can open the door to insights regarding hidden, unconscious aspects of a particular issue.  It may also be used as a general reading for an insight into your interiority here and now.\n\n1- What is repressed\n2- The Yin card, your female (passive) aspect\n3- The Yang card, your male (active) aspect The meditation\n4- Insight into the body\n5- Insight into the heart \n7- Insight into the being\n8- Consciousness (understanding)",
  "6": "The Celtic Cross\nThis traditional layout is used for clarity on a specific issue as well as for general readings.  In the OSHO Zen Tarot, the positions of the cards have the following meaning:\n\n\n1- The issue\n2- Diminishing/ enhancing the issue, or clarifying/ obscuring the issue\n3- The unconscious influences\n4- The conscious influences\n5- Old patterns, the old way\n6- New patterns, moving into the new\n7- Self: your feelings and attitudes about the issue\n8- What you are attracting from the outside\n9- Your desires/denials\n10- Outcome/key",
  "7": "The Mirror\nThis spread is a more in depth approach to gaining insights into your relating with the other, whether the boss, the lover, the friend, the sister, the parent…. It offers an understanding of the life processes of each individual, as well as insights into what is happening between you.\n\nYou in the here/now:\n1- The Body\n2- The Heart\n3- The Mind\n\nPartner in the here/now:\n4- The Body\n5- The Heart\n6- The Mind\n\nOuter manifestation of the partnership\n7- Melting and merging (intimacy)\n8- The alchemy of togetherness (transformation)\n9- The blessings (benefits and gifts)\n\nInner spiritual purpose:\n10- Melting and merging (intimacy)\n11- The alchemy of togetherness (transformation)\n12- The blessings (benefits and gifts)",
  "8": "The Paradox\nShutile the deck of cards for a few minutes, Split the deck into three packs and select one. The top card of the stack you have chosen represents the here/now. The bottom card represents the past-life influences. \n\nFan the rest of this stack and select one more card. This card represents the insight into the paradox.",
  "9": "The Ankh\nThe Ankh tarot spread is based the ancient Egyptian ankh sign, a symbol of life also known as the “mirror of Venus”. As the ankh consists of a circle and a cross, the placement of cards affects their meanings. Cards which are placed on the circle of the ankh spread indicate a spiritual background and the root cause of happenings, while cards placed on the cross show how problems are manifested in real life, what can be done to avoid them and what they will bring.\n\n1&2- Two opposite impulses, beginnings or motives, that seem to block each other.\n3- Longtime reasons\n4- The latest reason (an excuse)\n5- Enlightenment (realization of the true meaning of events)\n6- Conclusions\n\nIf a person is able to attain enlightenment (5) and draw the necessary conclusions (6), you can reveal the other cards:\n\n7- The next step\n8- An unexpected discovery\n9- The Result"
};
