

const layoutData = {
  "1": "A Single Card\nFor insights into any situation that relates to your living today. Or as a basis for meditating now.",
  "2": "Three Card Spread\nThere are many variations of three card spread.\n\nProblem Solving/Decision Making Approach:\nLeft Card: The Context – This card reflects a general overview of the Querent’s present situation.\nCenter Card: The Focus – This card reflects the circumstances of the situation, and what lessons can be learned. These lessons may be positive or negative depending on the card.\nRight Card: The Outcome – This card shows suggests a method of action for the Querent.\n\nTimeline Approach:\nLeft Card: The Past – This card shows the Querent’s past experiences, the ones that cast a light on the current situation.\nCenter Card: The Present – This card reveals what the Querent is feeling and experiencing at the moment.\nRight Card: The Future – This card tells the course of action that will serve the Querent’s highest good, based on the first two cards.\n\nSome other variations:\n\nLinear spreads:\nYou, Your Path, Your Potential\nYou, Relationship, Partner\nSituation, Action, Outcome\nIdea, Process, Aspiration\n\nBalanced Spreads:\nMind, Body, Spirit\nPhysical State, Emotional State, Spiritual State\nSubconscious, Conscious, Super Conscious\nOption 1, Option 2, Option 3\nWhat I think, What I feel, What I do\n\nFoundational Spreads:\nGiven your <b><i>strengths</i></b> and <b><i>weaknesses</i></b>, this is my <b><i>advice</i></b>.\nGiven <b><i>what worked well</i></b>, and <b><i>what didn’t work well</i></b>, this is the <b><i>key lesson</i></b>.\nGiven that <b><i>this brings you together</i></b>, and that <b><i>this pulls you apart</i></b>, you must <b><i>focus on this</i></b>.\nGiven that <b><i>you want this from the relationship</i></b>, and <b><i>your partner wants this</i></b>, <b><i>your relationship is heading towards this</i></b>.\nGiven <b><i>Option 1</i></b> and <b><i>Option 2</i></b>, This is <b><i>what you need to know to make a decision</i></b>.\n\nCrossed Spreads:\nSituation, Obstacle, Advice\nAspiration, Obstacle, How to Overcome\nOpportunities, Challenges, Outcome\nThesis, Antithesis, Synthesis",
  "3": "Relating - \"A Quickie\"\nThis spread offers a spontaneous insight into your relating with the other, whether \"the other\" is the boss, the lover, the friend, the sister, the parent...\n\n1- You and what you are contributing to the relating here/now.\n2- The other, the other's input to the relating \n3- The composite energies\n4- The insight",
  "4": "The Diamond\nThis layout can be helpful in bringing more clarity to a specific issue.\n\n1- The issue\n2- Internal influence that you are unable to see\n3- External influence of which you are aware\n4- What is needed for resolution \n5- Resolution: the understanding",
  "5": "The Flying Bird\nThis layout is designed in the shape of a bird taking flight.  The cards chosen and placed in the left wing symbolize and indicate to us something about our feminine, receptive energy, while the right wing symbolizes our masculine, active energy.  The first card picked is the initiator of the flight and stems from this active side.  Each succeeding card responds to the previous one and lifts \"the bird\" higher, allowing the questioner to move into greater clarity and inner understanding.\n\n1- Here & now — the 'lift-off\" card\n2- The resistance card - 'fear of flying' \n3- Response-ability to the fear\n4- Inner support (intuition) of responsibility\n5- External support (intelligent action responding to the intuition)\n6- Relaxation and acceptance\n7- Arrival at a new level of awareness",
  "6": "The Key\n\"The Key\" layout can open the door to insights regarding hidden, unconscious aspects of a particular issue.  It may also be used as a general reading for an insight into your interiority here and now.\n\n1- What is repressed\n2- The Yin card, your female (passive) aspect\n3- The Yang card, your male (active) aspect The meditation\n4- Insight into the body\n5- Insight into the heart \n7- Insight into the being\n8- Consciousness (understanding)",
  "7": "The Celtic Cross\nThis traditional layout is used for clarity on a specific issue as well as for general readings.  In the OSHO Zen Tarot, the positions of the cards have the following meaning:\n\n\n1- The issue\n2- Diminishing/ enhancing the issue, or clarifying/ obscuring the issue\n3- The unconscious influences\n4- The conscious influences\n5- Old patterns, the old way\n6- New patterns, moving into the new\n7- Self: your feelings and attitudes about the issue\n8- What you are attracting from the outside\n9- Your desires/denials\n10- Outcome/key",
  "8": "The Mirror\nThis spread is a more in depth approach to gaining insights into your relating with the other, whether the boss, the lover, the friend, the sister, the parent…. It offers an understanding of the life processes of each individual, as well as insights into what is happening between you.\n\nYou in the here/now:\n1- The Body\n2- The Heart\n3- The Mind\n\nPartner in the here/now:\n4- The Body\n5- The Heart\n6- The Mind\n\nOuter manifestation of the partnership\n7- Melting and merging (intimacy)\n8- The alchemy of togetherness (transformation)\n9- The blessings (benefits and gifts)\n\nInner spiritual purpose:\n10- Melting and merging (intimacy)\n11- The alchemy of togetherness (transformation)\n12- The blessings (benefits and gifts)",
  "9": "The Paradox\nShutile the deck of cards for a few minutes, Split the deck into three packs and select one. The top card of the stack you have chosen represents the here/now. The bottom card represents the past-life influences. \n\nFan the rest of this stack and select one more card. This card represents the insight into the paradox.",
  "10": "The Ankh\nThe Ankh tarot spread is based the ancient Egyptian ankh sign, a symbol of life also known as the “mirror of Venus”. As the ankh consists of a circle and a cross, the placement of cards affects their meanings. Cards which are placed on the circle of the ankh spread indicate a spiritual background and the root cause of happenings, while cards placed on the cross show how problems are manifested in real life, what can be done to avoid them and what they will bring.\n\n1&2- Two opposite impulses, beginnings or motives, that seem to block each other.\n3- Longtime reasons\n4- The latest reason (an excuse)\n5- Enlightenment (realization of the true meaning of events)\n6- Conclusions\n\nIf a person is able to attain enlightenment (5) and draw the necessary conclusions (6), you can reveal the other cards:\n\n7- The next step\n8- An unexpected discovery\n9- The Result",
  "11": "Shadow Work Spread\n1- What do I need to know about this part of my shadow?\n2- What is it preventing me from accessing?\n3 -How does this shadow manifest as a problem?\n4- What’s a good next step I can take to bring this shadow to light?\n5- How can I most usefully approach this shadow work?\n6- What can I expect to feel in the early phase of this process?\n\nAlternatively (simpler version):\n1- Shadow Aspect: Reveals hidden or unconscious aspects of the self that need to be acknowledged or integrated.\n2- Root Cause: Identifies the underlying or root cause of issues, patterns, or fears that may be holding you back.\n3- Resolution: Offers insights, guidance, or potential paths forward for healing, growth, or transformation.",
  "12": "Horseshoe Spread\nProvides insights into a particular situation or question from multiple angles, including past influences, current challenges, and future opportunities.\n\nUseful if you are looking for strategies on how to reach the desired outcome.  It’s not just a case of \"This is the outcome – good luck!\" You are given rich information about the obstacles and how to overcome them.\n\n1. Past\n2. Present\n3. Future\n4. Attitude towards question\n5. Other influences\n6. Obstacles\n7. Likely outcome",
  "13": "Decision-Making Spread\nDesigned to help with decision-making, this spread typically involves:\n\n-laying out cards representing different options or factors to consider, \n-along with potential outcomes for each choice."
};